# Generated by Django 3.2.13 on 2022-11-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221109_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desciption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
